# Generated by Django 3.2.8 on 2021-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20211030_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер заказа')),
                ('id_manager', models.CharField(max_length=10, verbose_name='ID менеджера')),
                ('data_orders', models.DateTimeField(verbose_name='Дата заказа')),
                ('price', models.CharField(max_length=10, verbose_name='Сумма заказа')),
                ('paid', models.CharField(max_length=10, verbose_name='Оплачено')),
                ('debt', models.CharField(max_length=10, verbose_name='Долг')),
                ('name_client', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('update_date', models.DateTimeField(verbose_name='Дата обновления')),
                ('manager', models.CharField(max_length=50, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=10, verbose_name='Номер заказа')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('descriptions', models.CharField(max_length=250, verbose_name='Описание')),
                ('brand', models.CharField(max_length=50, verbose_name='Бранд')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('quantity', models.CharField(max_length=10, verbose_name='Кличество')),
                ('price_product', models.CharField(max_length=10, verbose_name='Стоимость товара')),
                ('date_deadline', models.DateTimeField(verbose_name='Дата отгурзки')),
                ('distributor', models.CharField(max_length=50, verbose_name='Дистрибьютер')),
                ('order_distributer', models.CharField(max_length=50, verbose_name='Номер у дистрибьютера')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий к товару')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товар',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='dump_json',
            options={'ordering': ('-id',), 'verbose_name': 'Дамп Json', 'verbose_name_plural': 'Дамп Json'},
        ),
    ]
