# Generated by Django 3.2.8 on 2021-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20211103_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_manager', models.CharField(max_length=10, verbose_name='ИД покупателя')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('mobile', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Менеджеры',
                'verbose_name_plural': 'Менеджер',
                'ordering': ('-id',),
            },
        ),
    ]
