# Generated by Django 3.2.8 on 2021-11-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_managers_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=10, verbose_name='Номер заказа')),
                ('number_product', models.CharField(max_length=10, verbose_name='Номер позиции')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('descriptions', models.CharField(max_length=250, verbose_name='Описание')),
                ('brand', models.CharField(max_length=50, verbose_name='Бранд')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('quantity', models.CharField(max_length=10, verbose_name='Кличество')),
                ('price_product', models.CharField(max_length=10, verbose_name='Стоимость товара')),
                ('date_deadline', models.DateTimeField(verbose_name='Дата отгурзки')),
                ('distributor', models.CharField(max_length=50, verbose_name='Дистрибьютер')),
                ('order_distributer', models.CharField(max_length=50, verbose_name='Номер у дистрибьютера')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий к товару')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товар',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='dump_json',
            options={'ordering': ('-id',), 'verbose_name': 'Дамп Json', 'verbose_name_plural': 'Дамп Json'},
        ),
    ]
