# Generated by Django 3.2.8 on 2021-11-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_managers_shop_id_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers_shop',
            name='id_manager',
            field=models.CharField(max_length=10, verbose_name='ИД менеджера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_deadline',
            field=models.DateTimeField(verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.CharField(max_length=10, verbose_name='Цена продажи'),
        ),
    ]
