# Generated by Django 3.2.8 on 2021-11-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20211103_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_product',
            field=models.CharField(default='', max_length=10, verbose_name='Номер позиции'),
        ),
    ]
