# Generated by Django 3.2.8 on 2021-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_product_number_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_table_orders', models.CharField(max_length=10, verbose_name='Количество отображаемых заказов по умолчанию')),
                ('name_file', models.CharField(max_length=100, verbose_name='Название файлов импорта')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
