# Generated by Django 3.2.8 on 2021-11-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20211112_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('id',), 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказ'},
        ),
    ]
