# Generated by Django 3.2.8 on 2021-11-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
