# Generated by Django 3.2.8 on 2021-11-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-id',), 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
