# Generated by Django 3.2.8 on 2021-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_auto_20211117_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_cat', models.CharField(max_length=20, verbose_name='Каталожный номер')),
                ('brand', models.CharField(max_length=150, verbose_name='Бранд')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('cuantity', models.CharField(max_length=10, verbose_name='Количество')),
                ('price', models.CharField(max_length=150, verbose_name='Цена')),
            ],
        ),
    ]
