# Generated by Django 3.2.8 on 2021-11-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_number_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number_catalog',
            options={'ordering': ('id',), 'verbose_name': 'Экспорт', 'verbose_name_plural': 'Экспорт'},
        ),
    ]
