# Generated by Django 3.2.8 on 2021-11-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_number_catalog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('data_orders',), 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказ'},
        ),
    ]
